name: BetterKeyboard
options:
  bundleIdPrefix: com.betterkeyboard
  deploymentTarget:
    iOS: "18.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"

targets:
  BetterKeyboard:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - "**/*.example.swift"
      - path: Shared
        excludes:
          - "**/*.example.swift"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.betterkeyboard.app
        INFOPLIST_FILE: Config/App-Info.plist
        CODE_SIGN_ENTITLEMENTS: Config/BetterKeyboard.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: KeyboardExtension

  KeyboardExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: KeyboardExtension
      - path: Shared
        excludes:
          - "**/*.example.swift"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.betterkeyboard.app.keyboard
        INFOPLIST_FILE: Config/KeyboardExtension-Info.plist
        CODE_SIGN_ENTITLEMENTS: Config/KeyboardExtension.entitlements
        SKIP_INSTALL: true
