name: BetterKeyboard
options:
  bundleIdPrefix: com.betterkeyboard
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  BetterKeyboard:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.betterkeyboard.app
        INFOPLIST_FILE: Config/App-Info.plist
        CODE_SIGN_ENTITLEMENTS: Config/BetterKeyboard.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: KeyboardExtension

  KeyboardExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: KeyboardExtension
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.betterkeyboard.app.keyboard
        INFOPLIST_FILE: Config/KeyboardExtension-Info.plist
        CODE_SIGN_ENTITLEMENTS: Config/KeyboardExtension.entitlements
        SKIP_INSTALL: true
